### ISSUE TITLE
PN532 module not detecting as emulated tag with Nano 33 BLE to Android

### ISSUE THREAD

**Issue by liswifi** [Seeed-Studio/PN532#139] opened 2023-03-05 23:45 UTC
It hasn't been detecting the PN532 at all while using the emulate_tag_ndef.ino example from this library. 

I find it strange that it compiles but doesn't detect the module. Lots of 'unused variable' and 'redefined variable' warnings appear during compilation but I'm unsure why. Here is a pastebin of the compile: [SeedStudio PN532 emulate_tag_ndef.ino](https://pastebin.com/KGHNu9ha)

Board: Arduino Nano 33 BLE Sense
OS: mbedOS Nano (33 BLE)
SPI connection

**Comment by Jenibluere** [comment] 2023-03-18 12:54
Hey, if you follow the steps outlined in this issue here, you can get it to work: https://github.com/Seeed-Studio/PN532/issues/88

I plan on making my own pull request with the fixed code, so will link to that when done.

**Comment by jlkalberer** [comment] 2023-09-04 15:25
@Jenibluere - what steps are you suggesting? There are many different ideas on how to solve in that thread.

**Comment by Cincinnatu** [comment] 2024-10-16 14:09
Has this issue been resolved? If not, I will try to solve the problem soon.

**Comment by jlkalberer** [comment] 2024-10-16 21:17
Yes, tag emulation is basically broken for iOS and Android at this point.

Every once in a while I can get a successful read (Android) but in general it's broken.

**Comment by Cincinnatu** [comment] 2024-10-17 08:35
It seems that some systems and phones do not support it.

**Comment by Lesords** [comment] 2024-11-04 02:30
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Closed as completed by Lesords** 2024-11-04 02:30 UTC
Labels: UAY, PN532

**Comment by jlkalberer** [comment] 2024-11-04 02:38
No, it's not that phones don't support this chip. The issue is that this code doesn't do the full handshake with error handling so most of the time the read fails. I've looked at logcat and I've seen a ton of errors since the code is missing parts of the protocol.
