### ISSUE TITLE
How do I specify gpios for wire library?

### ISSUE THREAD

**Issue by zhekch** [Seeed-Studio/PN532#136] opened 2022-12-06 19:00 UTC
I am using esp32, and need to use Wire library with connection such as `Wire.begin(15,4)` for I2C. Didn't find the mention of this in the library.

**Comment by Cincinnatu** [comment] 2024-10-16 14:01
The Wire library for ESP32 allows you to specify custom I2C pins using Wire.begin(SDA, SCL). I'm not sure what you're asking, so if the issue is still not resolved, please provide more information.

**Comment by Lesords** [comment] 2024-11-04 02:30
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Closed as completed by Lesords** 2024-11-04 02:30 UTC
Labels: UAY, PN532
